Introduce leancode azure identity
leancodepl/corelibrary pull request #306
Opened 2021-08-13 07:36 UTC by marcin-dardzinski

I'd like to standardize the way we authenticate to Azure services and a single source of truth when it comes to configuration. I opted out of `DefaultAzureCredential` as we have little control of how it behaves. So, `DefaultLeanCodeCredential` it is with all options used by us set explicitly. I also didn't use `ChainedTokenCredential`, we usually do not use a chain an explicitly use one method. 

The second KV and IdentityServre related change is that key vault clients are no longer created by `SigningService` instead they're expected to be registered in the DI container. It plays nicely with this pattern https://docs.microsoft.com/en-us/dotnet/azure/sdk/dependency-injection#register-client. The only think it bothers me is that it'd mean that we can have only one `CryptographyClient` registered (and it's created for a concrete key), but we can use named clients to overcome this limitation.

I also removed recently added key vault configuration key overrides, I think that if we need such thing, it's better to simply pass `TokenCredential` secrets need to use.

I'll prepare a sample of how it'd look like.

2021-08-13 09:46 UTC, marcin-dardzinski commented
Ok, I decided to switch to named clients, here's the sample of how it'd get registered in the app https://bitbucket.org/leancode-team/tools/commits/52a17c81f298d3772ed5371be34a108b300b077e?at=feature/update-template#chg-templates/content/backend/src/Apps/LNCDApp.MainApp/Config.cs

2021-08-16 08:46 UTC, Saancreed requested changes
Comments, plus `DisposeAsync` in `LeanCodeTestFactory.cs` should be fixed as well.

2021-08-16 08:46 UTC, Saancreed commented on Directory.Build.targets
> +    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.1.0" />
This probably shouldn't be included repo–wide.

2021-08-16 08:46 UTC, Saancreed commented on src/Infrastructure/LeanCode.AzureIdentity/DefaultLeanCodeCredential.cs
> +        else if (config.UseAzureCLI)
I find it not very obvious that this flag is completely ignored when `UseManagedIdentity` is set. Can make it a tri–state enum or at least throw an exception when attempting to create such `AzureCredentialConfiguration`?

2021-08-16 08:46 UTC, Saancreed commented on src/Infrastructure/LeanCode.AzureIdentity/AzureCredentialConfiguration.cs
> +    public string? TenantId { get; init; }
I'd reorder this to match the order of initializers in `DefaultLeanCodeCredential.Create`, so `TenantId` before `ClientId`.

Same with keys below.

2021-08-16 08:46 UTC, Saancreed commented on src/Infrastructure/LeanCode.AzureIdentity/DefaultLeanCodeCredential.cs
> +            ClientSecret = Get<string>(AzureCredentialConfiguration.TenantIdKey),
`TenantIdKey`? Looks like a happy copy paste accident.

2021-08-16 08:46 UTC, Saancreed commented on src/Infrastructure/LeanCode.AzureIdentity/DefaultLeanCodeCredential.cs
> +            ClientSecret = GetEnv(AzureCredentialConfiguration.TenantIdKey),
Another happy copy paste accident here.

2021-08-16 08:46 UTC, Saancreed commented on src/Core/LeanCode.Components.Startup/IHostBuilderExtensions.cs
> +        public const string VaultKey = "KeyVault:VaultUrl";
We can rename it to `VaultUrlKey` to be more precise. Also I'd keep overrides that allow us to use another key.

2021-08-16 09:14 UTC, Saancreed commented on Directory.Build.targets
> +    <PackageReference Update="Microsoft.Extensions.Azure" Version="1.1.0" />
Now it's a duplicate of line 25 :upside_down_face:

2021-08-16 09:16 UTC, Saancreed commented on src/Infrastructure/LeanCode.AzureIdentity/AzureCredentialConfiguration.cs
> +    public string? TenantId { get; init; }
Only half done.

2021-08-16 11:34 UTC, Saancreed approved these changes

2021-08-16 12:37 UTC, merged