Upgrade to MassTransit V8
leancodepl/corelibrary pull request #392
Opened 2022-03-31 12:04 UTC by Dragemil

Biggest breaking change was probably end of 3rd party DI containers support so now it relays mostly on `Microsoft.Extensions.DependencyInjection`. Tests are passing so it seems it is fine.

Be prepared for the `Newtonsoft.Json` purge, because it's high time to stop supporting both serializers.

I leave it in draft state, because it is a breaking change that needs to target v6.1 CoreLib branch which is not prepared yet.

2022-03-31 13:31 UTC, jakubfijalkowski commented
![image](https://user-images.githubusercontent.com/357096/161066558-9232d558-89e5-4a64-9c4f-45a3a86da3b8.png)
Codecov, go home, you're drunk...

2022-03-31 16:44 UTC, jakubfijalkowski approved these changes

2022-04-01 06:42 UTC, marcin-dardzinski commented on src/Domain/LeanCode.DomainModels.MassTransitRelay/IPipeContextServiceResolver.cs
>      public class AutofacPipeContextServiceResolver : IPipeContextServiceResolver
Do we need this class anymore? It was used when we had to use service locator pattern in filters, but now we rely on MT.

2022-04-01 07:02 UTC, marcin-dardzinski commented on src/Domain/LeanCode.DomainModels.MassTransitRelay/InjectLifetimeScopeFilter.cs
> +            if (!context.TryGetPayload(out Autofac.Extensions.DependencyInjection.AutofacServiceProvider? scopeProvider))
Now I wonder if this class is necessary too. We needed it to patch MT Autofac integration, but right now it's all Microsoft.Extensions

2022-04-01 07:06 UTC, jakubfijalkowski requested changes
@marcin-dardzinski makes a great point - since MT does not use Autofac anymore, we should try to remove all of our Autofac or confirm that we won't be able to.

2022-04-01 08:21 UTC, Dragemil commented
I attempted to remove everything related to MT Autofac integration and I hope it is not needed anymore.

2022-04-01 08:22 UTC, jakubfijalkowski commented
Let's not put the change to faith and add tests for that (if we don't have already) :)

2022-04-01 08:42 UTC, Dragemil commented
Alright, bad wording - `ScopedFiltersTests` are testing that and they're passing.

2022-04-01 09:02 UTC, jakubfijalkowski approved these changes

2022-04-01 09:38 UTC, marcin-dardzinski approved these changes

2022-04-04 06:05 UTC, merged